# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
# Script needs a resource group to deploy to with an associated federated credential. 
# @TODO: Resource Group variable
# Create secrets in advance in GitHub as Actions secrets:
# AZURE_CLIENT_ID: The appId from the service principal creation.
# AZURE_CLIENT_SECRET: The password from the service principal creation.
# AZURE_TENANT_ID: The tenant from the service principal creation.
# AZURE_SUBSCRIPTION_ID: The subscription ID you retrieved.
# AZURE_RESOURCE_GROUP: The resource group you will deploy to. 

name: Set up new test environment with Python app to Azure Web App - UUFSolver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade gunicorn uvicorn
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r .env.sample

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
            !antenv/

  deploy_infrastructure:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: test
      url: ${{ steps.deploy-to-uuf-solver-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Check if Azure Cognitive Services account exists
        id: check_account
        run: |
          az cognitiveservices account show --name DeepSearchUUF-${{ github.run_id }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || echo "Account does not exist"
        continue-on-error: true
  
      - name: Set account existence variable
        id: set_account_existence
        run: |
          if az cognitiveservices account show --name DeepSearchUUF-${{ github.run_id }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} > /dev/null 2>&1; then
            echo "ACCOUNT_EXISTS=true" >> $GITHUB_ENV
          else
            echo "ACCOUNT_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Deploy Bicep template
        id: deploy_bicep
        run: |
          az deployment group create \
            --name bicep-deployment-${{ github.run_id }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file main.bicep \
            --parameters @parameters.json \
                         clientId=${{ secrets.AZURE_CLIENT_ID }} \
                         clientSecret=${{ secrets.AZURE_CLIENT_SECRET }}
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Get deployment outputs
        id: get_outputs
        run: |
            outputs=$(az deployment group show --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name bicep-deployment-${{ github.run_id }} --query properties.outputs)
            echo "WEB_APP_NAME=$(echo $outputs | jq -r .webAppName.value)" >> $GITHUB_ENV
            echo "RESOURCE_TOKEN=$(echo $outputs | jq -r .resourceToken.value)" >> $GITHUB_ENV
  
        env:
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      # - name: Check if Search Data Reader role assignment exists
      #   id: check_search_data_reader_assignment
      #   run: |
      #         if az role assignment list --scope $(az search service show --name mysearch-${{ env.RESOURCE_TOKEN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query id -o tsv) --assignee $(az identity show --name uuf-solver-identity-${{ env.RESOURCE_TOKEN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query principalId -o tsv) --role "Search Data Reader" | grep -q "roleDefinitionId"; then
      #           echo "SEARCH_DATA_READER_ASSIGNMENT_EXISTS=true" >> $GITHUB_ENV
      #         else
      #           echo "SEARCH_DATA_READER_ASSIGNMENT_EXISTS=false" >> $GITHUB_ENV
      #         fi
    
      # - name: Create Search Data Reader role assignment if not exists
      #   if: env.SEARCH_DATA_READER_ASSIGNMENT_EXISTS == 'false'
      #   run: |
      #         az role assignment create --assignee $(az identity show --name uuf-solver-identity-${{ env.RESOURCE_TOKEN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query principalId -o tsv) --role "Search Data Reader" --scope $(az search service show --name mysearch-${{ env.RESOURCE_TOKEN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query id -o tsv)
    
      - name: Check if Contributor role assignment exists
        id: check_contributor_assignment
        run: |
          if az role assignment list --scope $(az group show --name ${{ secrets.AZURE_RESOURCE_GROUP }} --query id -o tsv) --assignee $(az identity show --name uuf-solver-identity-${{ env.RESOURCE_TOKEN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query principalId -o tsv) --role "b24988ac-6180-42a0-ab88-20f7382dd24c" | grep -q "roleDefinitionId"; then
            echo "CONTRIBUTOR_ASSIGNMENT_EXISTS=true" >> $GITHUB_ENV
          else
            echo "CONTRIBUTOR_ASSIGNMENT_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Contributor role assignment if not exists
        if: env.CONTRIBUTOR_ASSIGNMENT_EXISTS == 'false'
        run: |
          az role assignment create --assignee-object-id $(az identity show --name uuf-solver-identity-${{ env.RESOURCE_TOKEN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query principalId -o tsv) --role "b24988ac-6180-42a0-ab88-20f7382dd24c" --scope $(az group show --name ${{ secrets.AZURE_RESOURCE_GROUP }} --query id -o tsv) --assignee-principal-type ServicePrincipal
    
  configure_web_app:
    runs-on: ubuntu-latest
    needs: deploy_infrastructure

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Register Azure AD application
        id: register_app
        run: |
          appName="UUF-Solver"
          redirectUri="https://${{ env.WEB_APP_NAME }}.azurewebsites.net/.auth/login/aad/callback"
          appRegistration=$(az ad app create --display-name $appName --reply-urls $redirectUri --available-to-other-tenants false --oauth2-allow-implicit-flow true --required-resource-accesses @manifest.json)
          clientId=$(echo $appRegistration | jq -r '.appId')
          objectId=$(echo $appRegistration | jq -r '.id')
          echo "CLIENT_ID=$clientId" >> $GITHUB_ENV
          echo "OBJECT_ID=$objectId" >> $GITHUB_ENV

      - name: Create client secret
        id: create_secret
        run: |
          clientSecret=$(az ad app credential reset --id ${{ env.CLIENT_ID }} --append --query password -o tsv)
          echo "CLIENT_SECRET=$clientSecret" >> $GITHUB_ENV

      - name: Assign API permissions
        run: |
          az ad app permission add --id ${{ env.CLIENT_ID }} --api 00000003-0000-0000-c000-000000000000 --api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Scope
          az ad app permission grant --id ${{ env.CLIENT_ID }} --api 00000003-0000-0000-c000-000000000000
          az ad app permission admin-consent --id ${{ env.CLIENT_ID }}

      - name: Set AAD client secret
        run: |
          az webapp config appsettings set --name ${{ env.WEB_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings AAD_CLIENT_SECRET=${{ env.CLIENT_SECRET }}
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}


      - name: Zip artifact for deployment
        run: zip release.zip ./* -r .env.sample appsettings.json

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
            !antenv/

  deploy_web_app:
    runs-on: ubuntu-latest
    needs: configure_web_app

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT to true
        run: |
          az webapp config appsettings set --name ${{ env.WEB_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set environment variables from appsettings.json file
        run: |
          az webapp config appsettings set --name ${{ env.WEB_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings @appsettings.json
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Wait for app settings to take effect
        run: sleep 30
    
      - name: 'Deploy to UUFSolver Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-uuf-solver-webapp
        with:
          app-name: ${{ env.WEB_APP_NAME }}